#!/bin/sh
set -eu
go vet ./...
go test ./...
if [ "$(go env GOOS)" = darwin ]; then
    go vet -tags endpointsecurity ./...
    go test -tags endpointsecurity ./...
    go run -tags endpointsecurity . -test
else
    go run . -test
fi
